  name: Build My Application
  on: push
  jobs: 
    build:
      name: Build out App
      runs-on: ubuntu-latest
      steps:
        - name: Pull Code
          uses: actions/checkout@v2.3.4
        - name: Print Current Directory
          run: pwd
        - name: List Files in Directory
          run: ls